version: "3.7"

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  django:
    container_name: django_server
    build:
      context: ./server
      dockerfile: ./docker/development/Dockerfile
    hostname: server
    ports:
      - 8000:8000
    volumes:
      - ./server:/code
    depends_on:
      - postgres
    env_file: .env
    command: /start.sh
    networks:
      - db_network

  postgres:
    container_name: postgres_server
    image: postgres:latest
    networks:
      - db_network
    ports:
      - 5432:5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: b${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata

networks:
  db_network:
    driver: bridge
